# essa configuração é usada pelo JMX exporter (https://github.com/prometheus/jmx_exporter)

startDelaySeconds: 90
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
  - pattern: '.*'
