- name: Install packages
  gather_facts: No
  hosts: all

  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - zip
        - wget
        - unzip
        - git
      become: yes